// ...
try {
    problemFunction()
} catch (e: Exception) {
    println()
} 
// ...